### ISSUE TITLE
I need a meme

### ISSUE THREAD

**Issue by Soumili1818** [Soumili1818/HAcktoberfest.DIEMS#8]

**Comment by Sterling1320** [comment]
I can provide good memes

**Comment by Rushimalani13** [comment]
I can solve this issue.

**Comment by Ak-Krishna** [comment]
we can solve by new tech

**Comment by Sterling1320** [comment]
![image](https://user-images.githubusercontent.com/99576454/197229578-9a35ab03-1b6e-4f9a-998f-9f3754a7a447.png)

**Comment by YashrajM** [comment]
![kesariya-memes](https://user-images.githubusercontent.com/89199535/197230457-95302234-686d-4df5-baa6-d34624706cc1.jpg)
